config/routes.rb
Rails.application.routes.draw do
  root 'expenses#index'
  resources :expenses
  get 'max', to: 'expenses#max'
  get 'year_to_date', to: 'expenses#ytd'
  get 'six_months', to: 'expenses#six_months'
  get 'twelve_months', to: 'expenses#twelve_months'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: %i[ show edit update destroy ]

  # GET /expenses or /expenses.json
  def index
    # Loads expenses from current month by default
    start_date = Date.today.beginning_of_month
    end_date = Date.today.end_of_month
    @expenses = current_user.expenses.all.order(created_at: :asc).where(created_at: start_date..end_date)
  end

  def max
    @expenses = current_user.expenses.all.order(created_at: :asc)
  end

  def ytd
    current_year = Date.today.year
    start_date = Date.new(current_year,1,1)
    end_date = Date.new(current_year,12,31)
    @expenses = current_user.expenses.all.order(created_at: :asc).where(created_at: start_date..end_date)
  end

  def six_months
    start_date = Date.today - 6.months
    end_date = Date.today
    @expenses = current_user.expenses.all.order(created_at: :asc).where(created_at: start_date..end_date)
  end

  def twelve_months
    start_date = Date.today - 1.year
    end_date = Date.today
    @expenses = current_user.expenses.all.order(created_at: :asc).where(created_at: start_date..end_date)
  end

  # GET /expenses/1 or /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = current_user.expenses.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses or /expenses.json
  def create
    params = { 
      title: expense_params[:title],
      value: expense_params[:value].gsub(',','.'),
      created_at: expense_params[:created_at]
    }
    @expense = current_user.expenses.new(params)
    respond_to do |format|
      if @expense.save
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully created!" }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: "Expense was successfully destroyed!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:title, :value, :created_at)
    end

    def convert(value)
      return if value.nil?
      ActionController::Base.helpers.number_to_currency(value.round(2), unit: "R$ ", delimiter: ".", separator: ",")
    end

    def convert_date(date)
      date.strftime("%d/%m/%Y")
    end

    def group_expenses(expenses)
      expenses = expenses.map { |e| {date: e.created_at.strftime("%m/%d/%Y"), value: e.value} }
      expenses.group_by { |d| d[:date] }.transform_values { |values| values.reduce(0) { |sum, v| sum + v[:value] } }
    end

    helper_method :convert
    helper_method :convert_date
    helper_method :group_expenses
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true) do |form| %>
  
  <% if request.path =~ /new/ %>
    <h1>New Expense</h1>
  <% else %>
    <h1>Editing Expense</h1>
  <% end %>

  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h4>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message.gsub('Created at', 'Date') %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title, required: true %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :value, required: true %>
    <%= form.text_field :value, class: "form-control", placeholder: "R$ 0,00" %>
  </div>

  <div class="field form-group">
    <%= form.label :date, required: true %>
  <% if request.path =~ /new/ %>
    <%= form.text_field :created_at, class: "form-control", placeholder: "__/__/____", value: Date.today.strftime("%d/%m/%Y") %>
  <% else %>
    <%= form.text_field :created_at, class: "form-control", placeholder: "__/__/____", value: @expense.created_at.strftime("%d/%m/%Y") %>
  <% end %>
  </div>
  <br>
  <div class="actions">
  <% if request.path =~ /new/ %>
    <%= form.submit 'Create Expense', class: "btn btn-success" %>
  <% else %>
    <%= form.submit 'Save Expense', class: "btn btn-success" %>
  <% end %>
    <%= link_to 'Back', max_path, class: "btn btn-primary" %>
  </div>

<% end %>

app/views/expenses/_home.html.erb
<div class="notices">
    <p id="notice"><strong><%= notice %></strong></p>
</div>
<% if @expenses.present? %>
    <%= line_chart group_expenses(@expenses), colors: ["#198754", "#666"], curve: false %>
<% else %>
    <p style="text-align: center">
        Oops, it seems like you don't have any expenses yet...
    </p>
<% end %>
<br>
<div class="home-title">
    <% if request.path == "/expenses" || request.path == "/" %>
        <h4>Current Month</h4>
    <% else %>
        <h4><%= request.path.gsub("/","").gsub("_", " ").gsub('six', '6').gsub('twelve', '12').capitalize %></h4>
    <% end %>
</div>
<br>
<%= render 'periods' %>
<br>
<table class="table table-dark">
  <thead>
    <tr>
      <th>Title</th>
      <th>Value</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.title %></td>
        <td><%= convert(expense.value) %></td>
        <td><%= convert_date(expense.created_at) %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
      <tr>
        <td><strong>Total spent</strong></td>
        <td>
          <strong>
            <%= convert(@expenses.reduce(0) { |acc, item| acc + item.value  }) %>
          </strong>
        </td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
  </tbody>
</table>
<div class="bottom-button-group">
    <button type="button" class="btn btn-success">
    <%= link_to 'New Expense...', new_expense_path %>
    </button>
</div>

app/views/expenses/_periods.html.erb
<div class="btn-group-etc" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-outline-success"><%= link_to 'Max', max_path %></button>
  <button type="button" class="btn btn-outline-success"><%= link_to '12 months', twelve_months_path %></button>
  <button type="button" class="btn btn-outline-success"><%= link_to '6 months', six_months_path %></button>
  <button type="button" class="btn btn-outline-success"><%= link_to 'Year to Date', year_to_date_path %></button></button>
  <button type="button" class="btn btn-outline-success"><%= link_to 'Current Month', expenses_path %></button>
</div>

app/views/expenses/edit.html.erb
<%= render 'form', expense: @expense %>

app/views/expenses/index.html.erb
<%= render 'home' %>

app/views/expenses/max.html.erb
<%= render 'home' %>

app/views/expenses/new.html.erb
<%= render 'form', expense: @expense %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card text-center">
  <div class="card-body">
    <h4 class="card-title"><%= @expense.title %></h4>
    <h5 class="card-text"><%= convert(@expense.value) %></h5>
    <button class="btn btn-success"><%= link_to 'Edit', edit_expense_path(@expense) %></button>
    <button class="btn btn-success"><%= link_to 'New Expense', new_expense_path %></button>
    <button class="btn btn-success"><%= link_to 'Back', max_path %></button>
  </div>
</div>

app/views/expenses/six_months.html.erb
<%= render 'home' %>

app/views/expenses/twelve_months.html.erb
<%= render 'home' %>

app/views/expenses/ytd.html.erb
<%= render 'home' %>